# Generated by Django 5.1.5 on 2025-06-10 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('FRIEND_REQUEST', 'Friend Request'), ('SYSTEM', 'System'), ('PAYMENT', 'Payment'), ('GROUP', 'Group'), ('CUSTOM', 'Custom')], max_length=50)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('requires_response', models.BooleanField(default=False)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('DANGER', 'Danger')], default='PRIMARY', max_length=20)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.alert')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'status', 'category'], name='api_alert_user_id_843678_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['reference_id', 'reference_type'], name='api_alert_referen_c53971_idx'),
        ),
    ]
