# Generated by Django 5.2.2 on 2025-06-10 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertaction',
            name='alert',
        ),
        migrations.CreateModel(
            name='AlertReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_read_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AlertAction',
        ),
        migrations.AddIndex(
            model_name='alertreadstatus',
            index=models.Index(fields=['user', 'alert_type'], name='api_alertre_user_id_51b8a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertreadstatus',
            unique_together={('user', 'alert_type')},
        ),
    ]
