# Generated by Django 5.1.5 on 2025-06-12 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_alertaction_alert_alertreadstatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertreadstatus',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='alertreadstatus',
            index=models.Index(fields=['batch_id'], name='api_alertre_batch_i_40ea36_idx'),
        ),
        migrations.AddIndex(
            model_name='alertreadstatus',
            index=models.Index(fields=['read_at'], name='api_alertre_read_at_2c30bc_idx'),
        ),
    ]
