# Generated by Django 5.2.2 on 2025-06-11 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('regular', 'Regular Group'), ('trip', 'Trip Group')], db_index=True, default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='trip_status',
            field=models.CharField(blank=True, choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_type'], name='connections_group_t_fda06b_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['trip_status'], name='connections_trip_st_7b4033_idx'),
        ),
    ]
