# Generated by Django 5.1.5 on 2025-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_group_budget_group_destination_group_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isDarkMode',
            field=models.BooleanField(default=False),
        ),
    ]
