# Generated by Django 5.1.5 on 2025-06-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
