# Generated by Django 5.1.5 on 2025-06-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_remove_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
