# Generated by Django 5.1.5 on 2025-06-17 08:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0002_group_budget_group_destination_group_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#4CAF50', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(db_index=True, max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee')], default='INR', max_length=3)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('split_type', models.CharField(choices=[('equal', 'Equal Split'), ('exact', 'Exact Amount'), ('percentage', 'Percentage'), ('shares', 'Shares')], default='equal', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('expense_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='connections.group')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expense.expense')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shares', models.IntegerField(blank=True, null=True)),
                ('amount_paid_back', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='expense.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('settlement_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('paytm', 'Paytm'), ('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('settlement_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('expense_shares', models.ManyToManyField(blank=True, related_name='settlements', to='expense.expenseshare')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='connections.group')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_received', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='connections.group')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user1', 'user2'], name='expense_bal_user1_i_c74c3b_idx'), models.Index(fields=['user2', 'user1'], name='expense_bal_user2_i_99faa7_idx'), models.Index(fields=['user1', 'group'], name='expense_bal_user1_i_6b5e18_idx'), models.Index(fields=['user2', 'group'], name='expense_bal_user2_i_0d36a6_idx')],
                'unique_together': {('user1', 'user2', 'group')},
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date', 'is_deleted'], name='expense_exp_date_f5368a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'is_deleted'], name='expense_exp_group_i_b288b6_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_by', 'date'], name='expense_exp_created_2715cc_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_id'], name='expense_exp_expense_76e965_idx'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['expense', 'payer'], name='expense_exp_expense_78dc14_idx'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['payer', 'expense'], name='expense_exp_payer_i_c01e27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensepayment',
            unique_together={('expense', 'payer')},
        ),
        migrations.AddIndex(
            model_name='expenseshare',
            index=models.Index(fields=['expense', 'user'], name='expense_exp_expense_dbd927_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseshare',
            index=models.Index(fields=['user', 'expense'], name='expense_exp_user_id_8e2958_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expenseshare',
            unique_together={('expense', 'user')},
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['payer', 'payee'], name='expense_set_payer_i_5025b6_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['payee', 'payer'], name='expense_set_payee_i_8c35a7_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['created_at'], name='expense_set_created_e3fbac_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['settlement_id'], name='expense_set_settlem_e3638b_idx'),
        ),
    ]
