# Generated by Django 4.2.22 on 2025-06-24 19:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTotalBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_balances_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_balances_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user1', 'user2'], name='expense_use_user1_i_c1686e_idx'), models.Index(fields=['user2', 'user1'], name='expense_use_user2_i_dc5536_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
