# Generated by Django 5.1.5 on 2025-06-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_usertotalbalance'),
    ]

    operations = [
    ]
